# Generated by Django 5.0.4 on 2024-04-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_adress_record_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
